include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for password hack deny by wulishui
LUCI_DEPENDS:=+gawk +ipset +iptables +ip6tables +iptables-mod-iprange +diffutils +bash
LUCI_PKGARCH:=all
PKG_VERSION:=6.0.5
PKG_RELEASE:=20210314

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
