#!/bin/sh /etc/rc.common
#Copyright (C) 20190805 wulishui <wulishui@gmail.com>
#20190805-202105025

START=99
USE_PROCD=1
enable=$(uci get cowbping.cowbping.enabled 2>/dev/null)
delaytime=$(uci get cowbping.cowbping.delaytime 2>/dev/null)

start_instance() {
	procd_open_instance
	procd_set_param command /usr/bin/cowbpingd
	procd_set_param respawn
	procd_set_param stderr 1
	procd_close_instance
}

start_service() {
	stop_service
	[[ $enable != 1 ]] && return 1
	[[ -f /var/lock/cowbping ]] && return 1
	touch /var/lock/cowbping
	:>/tmp/log/cowbping.log
	kill -9 $(pgrep cowbpingd) >/dev/null 2>&1
	start_instance
	rm -f /var/lock/cowbping
}

service_triggers() {
	procd_add_reload_trigger 'cowbping'
}

stop_service() {
	kill -9 $(ps | grep 'cbp_cmd' | grep -v 'grep' | awk '{print $1}') >/dev/null 2>&1
	:>/tmp/log/cowbping.log
}

restart() {
	stop_service
	start
}

boot() {
	if [[ x$enable = x1 && x$delaytime != x ]]; then
		logger -t cowbping "延时 $delaytime秒启动 cowbping"
		sleep $delaytime
		restart
	else
		return 1
	fi
}
