#!/bin/sh /etc/rc.common
#Copyright (C) 20190805 wulishui <wulishui@gmail.com>
#20190805-202105025

START=99
USE_PROCD=1
enable=$(uci -q get cowbping.cowbping.enabled)
delaytime=$(uci -q get cowbping.cowbping.delaytime)

start_instance() {
	procd_open_instance
	procd_set_param command /usr/bin/cowbpingd
	procd_set_param respawn
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger 'cowbping'
}

start_service() {
	stop_service
	[ "$enable" != 1 -o -f /var/lock/cowbping ] && return 1
	touch /var/lock/cowbping
	:>/tmp/log/cowbping.log
	kill -9 $(ps | awk '/usr\/bin\/cowbpingd/{print $1}') >/dev/null 2>&1
	start_instance
	rm -f /var/lock/cowbping
}

stop_service() {
	kill -9 $(ps | awk '/usr\/bin\/cowbpingd/{print $1}') >/dev/null 2>&1
	kill -9 $(ps | awk '/etc\/config\/cbp_cmd/{print $1}') >/dev/null 2>&1
	:>/tmp/log/cowbping.log
}

restart() {
	stop_service
	start
}

boot() {
	if [ "$enable" = 1 -a -n "$delaytime" ]; then
		logger -t cowbping "延时 $delaytime秒启动 cowbping"
		sleep $delaytime
		start
	fi
}
