#!/bin/sh

uci -q batch <<-EOF>/dev/null
	delete ucitrack.@pwdHackDeny[-1]
	add ucitrack pwdHackDeny
	set ucitrack.@pwdHackDeny[-1].init=pwdHackDeny
	delete firewall.pwdHackDeny
	set firewall.pwdHackDeny=include
	set firewall.pwdHackDeny.type=script
	set firewall.pwdHackDeny.path=/etc/pwdHackDenysh.include
	commit firewall
	commit ucitrack
EOF

cat <<-EOF>/etc/sysupgrade.conf
	/etc/WEBbadip.log
	/etc/SSHbadip.log
	/etc/pwdHackDeny/
	EOF

rm -f /tmp/luci-indexcache
exit 0
