#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@softwarecenter[-1]
	add ucitrack softwarecenter
	set ucitrack.@softwarecenter[-1].init=softwarecenter
	commit ucitrack
EOF

rm -rf /tmp/luci-*
exit 0
