#!/bin/sh /etc/rc.common

START=95
cron_ini=/etc/init.d/cron
cron_file=/etc/crontabs/root

timedtask_get() {
    local command day enable month minute hour week
    config_get enable "$1" enable "0"
    config_get day "$1" day "*"
    config_get week "$1" week "*"
    config_get hour "$1" hour "*"
    config_get month "$1" month "*"
    config_get minute "$1" minute "0"
    config_get command "$1" command "echo 'Reboot schedule tested.'"
    [ -s "$cron_file" ] || mcronrst=1
    if [ "$enable" -eq 1 ]; then
        echo "$minute" | grep -Eq '\*$' && minute="0"
        echo "$minute $hour $day $month $week $command #timedtask" >> $cron_file
    fi
    [ -n "$mcronrst" ] && $cron_ini restart
}

start() {
    sed -i '/timedtask$/d' $cron_file
    config_load timedtask
    config_foreach timedtask_get "crontab"
}

stop() {
    sed -i '/timedtask/d' $cron_file
    $cron_ini restart
}
