include $(TOPDIR)/rules.mk

include $(INCLUDE_DIR)/package.mk

LUCI_TITLE:=LuCI support for Crontab
LUCI_DEPENDS:=
LUCI_PKGARCH:=all
PKG_NAME:=luci-app-timedtask
PKG_VERSION:=1.2
PKG_RELEASE:=20230131

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
