#!/bin/sh
[ -f /etc/init.d/cpufreq ] && chmod +x /etc/init.d/cpufreq
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@cpufreq[-1]
	add ucitrack cpufreq
	set ucitrack.@cpufreq[-1].init=cpufreq
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
