include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for white or black list
LUCI_DEPENDS:=
LUCI_PKGARCH:=all

PKG_VERSION:=2.2.8-20241216

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
