include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for white or black list
LUCI_DEPENDS:=+luci-lib-fs
LUCI_PKGARCH:=all

PKG_VERSION:=2.2.1-20231001

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
