#!/bin/sh /etc/rc.common
# Author=wulishui , 20200908-0915 ; <wulishui@gmail.com>

START=99
STOP=15

SERVICE_DAEMONIZE=1
CRON_FILE=/etc/crontabs/root

uci_get_by_type() {
	uci get rebootschedule.@crontab[$1].$2 2>/dev/null
}

start() {
	grep -q 'option enable .1.' /etc/config/rebootschedule && {
		[[ -s $CRON_FILE ]] || mcronrst=1
		sed -i '/rebootschedule/d' $CRON_FILE
		sum=$(grep -c 'config crontab' /etc/config/rebootschedule)
		for x in $(seq 0 $((sum-1))); do
			[[ `uci_get_by_type $x enable` -eq 1 ]] && {
				day=`uci_get_by_type $x day` || day="*"
				week=`uci_get_by_type $x week` || week="*"
				hour=`uci_get_by_type $x hour` || hour="*"
				month=`uci_get_by_type $x month` || month="*"
				minute=`uci_get_by_type $x minute` || minute="*"
				command=`uci_get_by_type $x command` || command="echo 'Reboot schedule tested.'"
				echo "$minute $hour $day $month $week $command #rebootschedule" >> $CRON_FILE
			}
		done
		[[ $mcronrst -eq 1 ]] && /etc/init.d/cron restart
	}
}

stop() {
	sed -i '/rebootschedule/d' $CRON_FILE
    /etc/init.d/cron restart
}
