include $(TOPDIR)/rules.mk

include $(INCLUDE_DIR)/package.mk

LUCI_TITLE:=LuCI support for tinynote
LUCI_DEPENDS:=
LUCI_PKGARCH:=all
PKG_NAME:=luci-app-tinynote
PKG_VERSION:=1.4
PKG_RELEASE:=20230606

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
