#!/bin/sh

uci -q batch <<-EOF >/dev/null
    delete ucitrack.@wizard[-1]
    add ucitrack wizard
    set ucitrack.@wizard[-1].init=wizard
    commit ucitrack
EOF

for file in dhcp network firewall wireless; do
    [ ! -f /etc/config/bk_$file -a -s /etc/config/$file ] && cp /etc/config/$file /etc/config/bk_$file
done

rm -f /tmp/luci-*

exit 0
