#!/bin/sh
touch /etc/config/wizard

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@wizard[-1]
	add ucitrack wizard
	set ucitrack.@wizard[-1].init=wizard
	commit ucitrack
EOF

[ ! -f /etc/config/bk_dhcp     -a -s /etc/config/dhcp     ] && cp /etc/config/dhcp /etc/config/bk_dhcp
[ ! -f /etc/config/bk_network  -a -s /etc/config/network  ] && cp /etc/config/network /etc/config/bk_network
[ ! -f /etc/config/bk_firewall -a -s /etc/config/firewall ] && cp /etc/config/firewall /etc/config/bk_firewall
[ ! -f /etc/config/bk_wireless -a -s /etc/config/wireless ] && cp /etc/config/wireless /etc/config/bk_wireless

rm -f /tmp/luci-indexcache

exit 0
