include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for webrestriction
LUCI_DEPENDS:=
LUCI_PKGARCH:=all
PKG_VERSION:=v1.0
PKG_RELEASE:=20210511

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
