#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@cowbping[-1]
	add ucitrack cowbping
	set ucitrack.@cowbping[-1].init=cowbping
	commit ucitrack
EOF

touch /etc/config/cbp_cmd
/etc/init.d/cowbping trace

rm -f /tmp/luci-*
exit 0
