#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@cowbpingd[-1]
	add ucitrack cowbpingd
	set ucitrack.@cowbpingd[-1].init=cowbpingd
	commit ucitrack
EOF

touch /etc/config/cbp_cmd

rm -f /tmp/luci-indexcache
exit 0
