include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-poweroff
LUCI_TITLE:=LuCI support for poweroff Router

LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
