include $(TOPDIR)/rules.mk

include $(INCLUDE_DIR)/package.mk

LUCI_TITLE:=LuCI support for Crontab
LUCI_DEPENDS:=
LUCI_PKGARCH:=all
PKG_NAME:=luci-app-rebootschedule
PKG_VERSION:=1.1
PKG_RELEASE:=20210607

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
