# Copyright (C) 2016 Openwrt.org
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for cow B ping by wulishui
LUCI_DEPENDS:=
LUCI_PKGARCH:=all
PKG_VERSION:=1.7
PKG_RELEASE:=20230131

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
