#!/bin/sh /etc/rc.common

START=52
STOP=10
include "/usr/bin/softwarecenter"

start() {
    SOFTWARECENTER >> "$log"
}

stop() {
    :
}

restart() {
    stop
    start
}

boot() {
    sleep ${a_delaytime}m
    start
}
