#!/bin/sh /etc/rc.common

START=52
STOP=10
include "/usr/bin/softwarecenter"
a_delaytime="$(uci -q get "softwarecenter.main.a_delaytime")"
a_delaytime="${a_delaytime:=0}m"

start() {
    type SOFTWARECENTER >/dev/null 2>&1 && SOFTWARECENTER >> "$log"
}

stop() {
    :
}

restart() {
    stop
    start
}

boot() {
    sleep "$a_delaytime"
    start
}
